export enum NotificationIntent {
   Generic = 0,
   FormAdded = 1,
   FormChanged = 2,
   SeatPackageAdded = 3,
   BulletinsAdded = 4,
   InstantRemark = 5,
   InstantComment = 6,
   InstantMessage = 7,
   InstantRemarkAddedOwner = 8,
   InstantRemarkAddedParticipating = 9,
   InstantCommentAddedOwner = 10,
   InstantCommentAddedParticipating = 11,
   ProgramsAdded = 12,
   InstantProgramRemark = 13,
   InstantProgramRemarkAddedOwner = 14,
   InstantProgramRemarkAddedParticipating = 15,
   InstantProgramRemarkReply = 16,
   InstantProgramRemarkReplyAddedOwner = 17,
   InstantThreadAddedFollowing = 18,
   InstantEntry = 19,
   InstantEntryAddedFollowing = 20,
   InstantFeedItem = 21,
   InstantOccasionRemark = 22,
   InstantOccasionRemarkAddedParticipating = 23,
   InstantOccasionRemarkReply = 24,
   InstantOccasionRemarkReplyAddedOwner = 25
}