export enum UIContentType {
   More = -1,
   Bulletins = 0,
   Documents = 1,
   Forms = 2,
   Occasions = 3,
   Conversations = 4,
   Programs = 5,
   Pins = 6,
   StaffHome = 7,
   Groups = 8,
   Social = 9,
   Notifications = 10,
   ActContacts = 11,
   ActDataPlus = 12,
   Forum = 13,
   Stack_1 = 14,
   Stack_2 = 15,
   Stack_3 = 16,
   Stack_4 = 17,
   Stack_5 = 18,
   Stack_6 = 19
}